version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: echo-mysql
    ports:
      - 3309:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./echo_db_create.sql:/docker-entrypoint-initdb.d/echo_db_create.sql
    environment:
      MYSQL_ROOT_PASSWORD: "echo"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci